#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Wed May  6 12:43:53 2015
#

import wx

# begin wxGlade: dependencies
import gettext
import time
import serial
import os,sys
from threading import *
ser = serial.Serial('/dev/ttyACM5', 19200)

# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class WorkerThread(Thread):
	def __init__(self):
           print "thread"
           """Init Worker Thread Class."""
           Thread.__init__(self)
           
           # This starts the thread running on creation, but you could
           # also make the GUI thread responsible for calling this
           self.start()

	def run(self):
		print 'run'
		
		global i,hum,tem,moi,bulb,fog,dip,fan
		print 'ser'
	 	while 1:
	 		
	 		
			hum = ser.readline()
			print hum
			tem = ser.readline()
			print tem
			moi = ser.readline()
			print moi
			bulb = ser.readline()
			print bulb
			fog = ser.readline()
			print fog
			dip = ser.readline()
			print dip
			fan = ser.readline()
			print fan
			time.sleep(3)


class MyFrame(wx.Frame, Thread):
    def __init__(self, *args, **kwds):
    
    	Thread.__init__(self)
      	WorkerThread()
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/1x1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_2 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/1x3.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_3 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/1x4.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_4 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/1x5.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_5 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/1x6.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_6 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/1x7.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_7 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/1x8.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_8 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/2x1.jpg", wx.BITMAP_TYPE_ANY))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_15 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_50 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_23 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_51 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_31 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_9 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/3x1.jpg", wx.BITMAP_TYPE_ANY))
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_16 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_52 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
       
        self.bitmap_24 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_53 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
       
        self.bitmap_32 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_10 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/4x1.jpg", wx.BITMAP_TYPE_ANY))
        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_17 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_41 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_26 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_42 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_33 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_11 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/5x1.jpg", wx.BITMAP_TYPE_ANY))
        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_18 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.button_5 = wx.Button(self, wx.ID_ANY, _("ON"))
        self.bitmap_25 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.button_6 = wx.Button(self, wx.ID_ANY, _("OFF"))
        self.bitmap_34 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_12 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/6x1.jpg", wx.BITMAP_TYPE_ANY))
        self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_19 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.button_7 = wx.Button(self, wx.ID_ANY, _("ON"))
        self.bitmap_27 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.button_8 = wx.Button(self, wx.ID_ANY, _("OFF"))
        self.bitmap_35 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_13 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/7x1.jpg", wx	.BITMAP_TYPE_ANY))
        self.text_ctrl_6 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_20 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.button_9 = wx.Button(self, wx.ID_ANY, _("ON"))
        self.bitmap_28 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.button_10 = wx.Button(self, wx.ID_ANY, _("OFF"))
        self.bitmap_36 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_14 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/8x1.jpg", wx.BITMAP_TYPE_ANY))
        self.text_ctrl_7 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.bitmap_21 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.button_11 = wx.Button(self, wx.ID_ANY, _("ON"))
        self.bitmap_29 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.button_12 = wx.Button(self, wx.ID_ANY, _("OFF"))
        self.bitmap_37 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_39 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_40 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_22 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.button_13 = wx.Button(self, wx.ID_ANY, _("QUIT"))
        self.bitmap_30 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.button_14 = wx.Button(self, wx.ID_ANY, _("RESET"))
        self.bitmap_38 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_43 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box1.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_44 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_45 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter0.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_46 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_47 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_48 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/box.jpg", wx.BITMAP_TYPE_ANY))
        self.bitmap_49 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/home/jain/Main Project/cut1/inter1.jpg", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        self.Bind(wx.EVT_BUTTON, self.fan_on, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.fan_off, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.bulb_on, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.bulb_off, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.fog_on, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.fog_off, self.button_10)
        self.Bind(wx.EVT_BUTTON, self.dip_on, self.button_11)
        self.Bind(wx.EVT_BUTTON, self.dip_off, self.button_12)
        self.Bind(wx.EVT_BUTTON, self.reset, self.button_14)
        
        self.start()
        # end wxGlade


    def run(self):
	while 1:
	    	global i,hum,tem,moi,bulb,fog,dip
	    	print 'while'	
	    	if hum.split()[0] == 'temperature':
			self.text_ctrl_1.SetValue(hum.split()[2])
		
		if hum.split()[0] == 'humidity':
			self.text_ctrl_3.SetValue(hum.split()[2])

		if hum.split()[0] == 'Moisture':
			self.text_ctrl_2.SetValue(hum.split()[2])
				
		if hum.split()[0] == 'bulb':
			self.text_ctrl_5.SetValue(hum.split()[2])
		if hum.split()[0] == 'fog':
			self.text_ctrl_6.SetValue(hum.split()[2])
		if hum.split()[0] == 'dip':
			self.text_ctrl_7.SetValue(hum.split()[2])
		if hum.split()[0] == 'fan':
			self.text_ctrl_4.SetValue(hum.split()[2])
		
		time.sleep(.3)
		
		if tem.split()[0] == 'temperature':
			self.text_ctrl_1.SetValue(tem.split()[2])

		if tem.split()[0] == 'humidity':
			self.text_ctrl_3.SetValue(tem.split()[2])
		
		if tem.split()[0] == 'Moisture':
			self.text_ctrl_2.SetValue(tem.split()[2])
				
		if tem.split()[0] == 'bulb':
			self.text_ctrl_5.SetValue(tem.split()[2])
		
		if tem.split()[0] == 'fog':
			self.text_ctrl_6.SetValue(tem.split()[2])
		if tem.split()[0] == 'dip':
			self.text_ctrl_7.SetValue(tem.split()[2])
		
		if tem.split()[0] == 'fan':
			self.text_ctrl_4.SetValue(tem.split()[2])
		
		
		
		
		if moi.split()[0] == 'temperature':
			self.text_ctrl_1.SetValue(moi.split()[2])

		if moi.split()[0] == 'humidity':
			self.text_ctrl_3.SetValue(moi.split()[2])

		if moi.split()[0] == 'Moisture':
			self.text_ctrl_2.SetValue(moi.split()[2])
				
		if moi.split()[0] == 'bulb':
			self.text_ctrl_5.SetValue(moi.split()[2])
		if moi.split()[0] == 'fog':
			self.text_ctrl_6.SetValue(moi.split()[2])
		if moi.split()[0] == 'dip':
			self.text_ctrl_7.SetValue(moi.split()[2])
		if moi.split()[0] == 'fan':
			self.text_ctrl_4.SetValue(moi.split()[2])
		
		
		
		
		if bulb.split()[0] == 'temperature':
			self.text_ctrl_1.SetValue(bulb.split()[2])

		if bulb.split()[0] == 'humidity':
			self.text_ctrl_3.SetValue(bulb.split()[2])

		if bulb.split()[0] == 'Moisture':
			self.text_ctrl_2.SetValue(bulb.split()[2])
				
		if bulb.split()[0] == 'bulb':
			self.text_ctrl_5.SetValue(bulb.split()[2])
		if bulb.split()[0] == 'fog':
			self.text_ctrl_6.SetValue(bulb.split()[2])
	 	if bulb.split()[0] == 'fog':
			self.text_ctrl_7.SetValue(bulb.split()[2])
		if bulb.split()[0] == 'fan':
			self.text_ctrl_4.SetValue(bulb.split()[2])
		
			
		
		
		
		if fog.split()[0] == 'temperature':
			self.text_ctrl_1.SetValue(fog.split()[2])

		if fog.split()[0] == 'humidity':
			self.text_ctrl_3.SetValue(fog.split()[2])

		if fog.split()[0] == 'Moisture':
			self.text_ctrl_2.SetValue(fog.split()[2])
				
		if fog.split()[0] == 'bulb':
			self.text_ctrl_5.SetValue(fog.split()[2])
		if fog.split()[0] == 'fog':
			self.text_ctrl_6.SetValue(fog.split()[2])
		if fog.split()[0] == 'dip':
			self.text_ctrl_7.SetValue(fog.split()[2])
		if fog.split()[0] == 'fan':
			self.text_ctrl_4.SetValue(fog.split()[2])	
		
		
			
		if dip.split()[0] == 'temperature':
			self.text_ctrl_1.SetValue(dip.split()[2])

		if dip.split()[0] == 'humidity':
			self.text_ctrl_3.SetValue(dip.split()[2])

		if dip.split()[0] == 'Moisture':
			self.text_ctrl_2.SetValue(dip.split()[2])
				
		if dip.split()[0] == 'bulb':
			self.text_ctrl_5.SetValue(dip.split()[2])
		if dip.split()[0] == 'fog':
			self.text_ctrl_6.SetValue(dip.split()[2])
		if dip.split()[0] == 'dip':
			self.text_ctrl_7.SetValue(dip.split()[2])
		if dip.split()[0] == 'fan':
			self.text_ctrl_4.SetValue(dip.split()[2])
		
    
    
    
    		if fan.split()[0] == 'temperature':
			self.text_ctrl_1.SetValue(fan.split()[2])

		if fan.split()[0] == 'humidity':
			self.text_ctrl_3.SetValue(fan.split()[2])

		if fan.split()[0] == 'Moisture':
			self.text_ctrl_2.SetValue(fan.split()[2])
				
		if fan.split()[0] == 'bulb':
			self.text_ctrl_5.SetValue(fan.split()[2])
		if fan.split()[0] == 'fog':
			self.text_ctrl_6.SetValue(fan.split()[2])
		if fan.split()[0] == 'dip':
			self.text_ctrl_7.SetValue(fan.split()[2])
		if fan.split()[0] == 'fan':
			self.text_ctrl_4.SetValue(fan.split()[2])
		time.sleep(3)
    
    
    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        self.text_ctrl_1.SetMinSize((85, 29))
        self.text_ctrl_2.SetMinSize((85, 29))
        self.text_ctrl_3.SetMinSize((85, 29))
        self.text_ctrl_4.SetMinSize((85, 29))
        self.text_ctrl_5.SetMinSize((85, 29))
        self.text_ctrl_6.SetMinSize((85, 29))
        self.text_ctrl_7.SetMinSize((85, 29))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(10, 7, 0, 0)
        grid_sizer_1.Add(self.bitmap_1, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_2, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_3, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_4, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_5, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_6, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_7, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_8, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_15, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_50, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_23, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_51, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_31, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_9, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_2, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_16, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_52, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_24, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_53, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_32, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_10, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_3, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_17, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_41, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_26, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_42, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_33, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_11, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_4, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_18, 0, 0, 0)
        grid_sizer_1.Add(self.button_5, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_25, 0, 0, 0)
        grid_sizer_1.Add(self.button_6, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_34, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_12, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_5, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_19, 0, 0, 0)
        grid_sizer_1.Add(self.button_7, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_27, 0, 0, 0)
        grid_sizer_1.Add(self.button_8, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_35, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_13, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_6, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_20, 0, 0, 0)
        grid_sizer_1.Add(self.button_9, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_28, 0, 0, 0)
        grid_sizer_1.Add(self.button_10, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_36, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_14, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_7, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_21, 0, 0, 0)
        grid_sizer_1.Add(self.button_11, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_29, 0, 0, 0)
        grid_sizer_1.Add(self.button_12, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_37, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_39, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_40, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_22, 0, 0, 0)
        grid_sizer_1.Add(self.button_13, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_30, 0, 0, 0)
        grid_sizer_1.Add(self.button_14, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_38, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_43, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_44, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_45, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_46, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_47, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_48, 0, 0, 0)
        grid_sizer_1.Add(self.bitmap_49, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        
    def bulb_on(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('H') # turns LED ON
	print("LED ON")
	self.text_ctrl_5.SetValue("ON")
        event.Skip()
        # end wxGlade
    def bulb_off(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('L') # turns LED ON
	print("LED OFF")
	self.text_ctrl_5.SetValue("OFF")
        event.Skip()
    def fog_on(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('S') # turns LED ON
	print("FOG HIGH")
	self.text_ctrl_6.SetValue("ON")
        event.Skip()
        
    def fog_off(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('R') # turns LED ON
	print("FOG LOW")
	self.text_ctrl_6.SetValue("OFF")
        event.Skip()
    def dip_on(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('DH') # turns LED ON
	print("DIP HIGH")
	self.text_ctrl_7.SetValue("ON")
        event.Skip()
    def dip_off(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('DL') # turns LED ON
	print("DIP LOW")
	self.text_ctrl_7.SetValue("OFF")
        event.Skip()
    def fan_on(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('X') # turns LED ON
	print("FAN HIGH")
	self.text_ctrl_4.SetValue("OFF")
        event.Skip()
    def fan_off(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('Y') # turns LED ON
	print("FAN LOW")
	self.text_ctrl_4.SetValue("OFF")
        event.Skip()
    
    def reset(self, event):  # wxGlade: MyFrame.<event_handler>
        ser.write('R') # turns LED ON
	print("RESET")
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
